version: "3.3"

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb_container
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=tpachato
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: spring-app:latest
    container_name: springboot_container
    restart: on-failure
    ports:
      - 5000:8089

    stdin_open: true
    tty: true
volumes:
  db: